apiVersion: v1
kind: Service
metadata:
  labels:
    app: thehive
  name: thehive
  namespace: thehive
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 30088
  selector:
    app: thehive
    ---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: thehive
spec:
  ports:
    - port: 9042
  selector:
    app: cassandra
    ---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: thehive
spec:
  ports:
    - port: 9200
  selector:
    app: elasticsearch
    ---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
  namespace: thehive
spec:
  ports:
    - port: 9000
  selector:
    app: minio