apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thehive-pvc
  namespace: thehive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Pas de opslagcapaciteit aan indien nodig
  storageClassName: longhorn  # Zorg ervoor dat de opslagklasse correct is