---
apiVersion: "v1"
kind: "Namespace"
metadata:
    name: thehive
    labels:
        name: thehive
---
#
# Create a role, `pod-reader`, that can list pods and
# bind the default service account in the namespace
# that the binding is deployed to to that role.
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thehive
  namespace: thehive
  labels:
    app: thehive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thehive
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: thehive
    spec:
      serviceAccountName: thehive
      containers:
        - name: thehive
          image: strangebee/thehive:5.4
          command:
            - "/opt/thehive/entrypoint"
            - "--secret"
            - "SuperSecretForKubernetes"
            - "--cql-hostnames"
            - "cassandra"
            - "--no-cql-wait"
            - "--no-config-cortex"
            - "--kubernetes"
            - "--index-backend"
            - "elasticsearch"
            - "--es-hostnames"
            - "elasticsearch"
            - "--s3-endpoint"
            - "http://minio:9000"
            - "--s3-access-key"
            - "minioadmin"
            - "--s3-secret-key"
            - "minioadmin"
            - "--s3-use-path-access-style"
            - "--cluster-min-nodes-count"
            - "0"
          ports:
            - containerPort: 9000
              name: http
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "PEKKO_MANAGEMENT_CLUSTER_BOOTSTRAP_CONTACT_POINT_DISCOVERY_DISCOVERY_METHOD"
              value: "kubernetes-api"
            - name: "PEKKO_MANAGEMENT_CLUSTER_BOOTSTRAP_CONTACT_POINT_DISCOVERY_REQUIRED_CONTACT_POINT_NR"
              value: "0"
            - name: "PEKKO_DISCOVERY_KUBERNETES_API_POD_LABEL_SELECTOR"
              value: "app=thehive"
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: "500m"
              memory: 512Mi
          volumeMounts:
            - name: thehive-storage
              mountPath: /var/lib/thehive  # Pas dit pad aan indien nodig
      volumes:
        - name: thehive-storage
          persistentVolumeClaim:
            claimName: thehive-pvc

#          startupProbe:
#            httpGet:
#              path: /api/v1/status/public
#              port: 9000
#            failureThreshold: 30
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /api/v1/status/public
#              port: 9000
#            periodSeconds: 10