apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: thehive
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 30089
  selector:
    app: thehive